### ISSUE TITLE
文件缺失

### ISSUE THREAD

**Issue by lyh0371** [yanghuanrong/RelaxPlus#1]
"build:ui": "rollup --config relax-plus/config/rollup.config.js",
    "build:css": "webpack --config relax-plus/config/style.config.js",

这两个对应的文件应该没有上传吧

**Comment by yanghuanrong** [comment]
这个配置是有问题的。在最新提交的代码中已经修改了。目前打包这块还有一些问题在做处理。

**Comment by yanghuanrong** [comment]
> ```
> "build:ui": "rollup --config relax-plus/config/rollup.config.js",
> "build:css": "webpack --config relax-plus/config/style.config.js",
> ```
> 
> 这两个对应的文件应该没有上传吧

这个配置是有问题的。在最新提交的代码中已经修改了。目前打包这块还有一些问题在做处理。

**Comment by lyh0371** [comment]
我看npm 是吧全部文件都上传了,是有些问题

**Comment by lyh0371** [comment]
期待作者完善,先star为敬

**Comment by yanghuanrong** [comment]
> 我看npm是吧全部文件都上传了，是某些问题

npm 中的包目前仅支持在 vue-cli中引入 vite这些的打包配置还有问题

**Comment by yanghuanrong** [comment]
> 期待作者完善,先star为敬

感谢支持
